package de.chaostheorybot.rykerconnect.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006874)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCEFF3)
val md_theme_light_onPrimaryContainer = Color(0xFF001F24)
val md_theme_light_secondary = Color(0xFF4A6267)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7EC)
val md_theme_light_onSecondaryContainer = Color(0xFF051F23)
val md_theme_light_tertiary = Color(0xFF525E7D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onTertiaryContainer = Color(0xFF0E1B37)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF7FAFB)
val md_theme_light_onBackground = Color(0xFF11191E)
val md_theme_light_surface = Color(0xFFF7FAFB)
val md_theme_light_onSurface = Color(0xFF11191E)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F1)
val md_theme_light_inverseSurface = Color(0xFF2E3132)
val md_theme_light_inversePrimary = Color(0xFF4FD8EB)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006874)
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF4FD8EB)
val md_theme_dark_onPrimary = Color(0xFF00363D)
val md_theme_dark_primaryContainer = Color(0xFF004F58)
val md_theme_dark_onPrimaryContainer = Color(0xFF97F0FF)
val md_theme_dark_secondary = Color(0xFFB1CBD0)
val md_theme_dark_onSecondary = Color(0xFF1C3438)
val md_theme_dark_secondaryContainer = Color(0xFF334B4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7EC)
val md_theme_dark_tertiary = Color(0xFFBAC6EA)
val md_theme_dark_onTertiary = Color(0xFF24304D)
val md_theme_dark_tertiaryContainer = Color(0xFF3B4664)
val md_theme_dark_onTertiaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF11191E)
val md_theme_dark_onBackground = Color(0xFFE1E3E3)
val md_theme_dark_surface = Color(0xFF11191E)
val md_theme_dark_onSurface = Color(0xFFE1E3E3)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_inverseOnSurface = Color(0xFF11191E)
val md_theme_dark_inverseSurface = Color(0xFFE1E3E3)
val md_theme_dark_inversePrimary = Color(0xFF006874)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF4FD8EB)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFC9C9C9)





/*
val md_theme_light_primary = Color(0xFF725C00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFE07F)
val md_theme_light_onPrimaryContainer = Color(0xFF231B00)
val md_theme_light_secondary = Color(0xFF685E40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF0E2BB)
val md_theme_light_onSecondaryContainer = Color(0xFF221B04)
val md_theme_light_tertiary = Color(0xFF616200)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE8EA30)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1D00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFEBE2CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4C4639)
val md_theme_light_outline = Color(0xFF7D7767)
val md_theme_light_inverseOnSurface = Color(0xFFF6F0E7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFEDC200)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF725C00)
val md_theme_light_outlineVariant = Color(0xFFCEC6B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFEDC200)
val md_theme_dark_onPrimary = Color(0xFF3C2F00)
val md_theme_dark_primaryContainer = Color(0xFF564500)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFE07F)
val md_theme_dark_secondary = Color(0xFFD3C6A1)
val md_theme_dark_onSecondary = Color(0xFF383016)
val md_theme_dark_secondaryContainer = Color(0xFF4F462A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF0E2BB)
val md_theme_dark_tertiary = Color(0xFFCCCD00)
val md_theme_dark_onTertiary = Color(0xFF323200)
val md_theme_dark_tertiaryContainer = Color(0xFF494900)
val md_theme_dark_onTertiaryContainer = Color(0xFFE8EA30)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE8E2D9)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE8E2D9)
val md_theme_dark_surfaceVariant = Color(0xFF4C4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFCEC6B4)
val md_theme_dark_outline = Color(0xFF979080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE8E2D9)
val md_theme_dark_inversePrimary = Color(0xFF725C00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFEDC200)
val md_theme_dark_outlineVariant = Color(0xFF4C4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFD100)
val AcidYellow = Color(0xFFF6F83F)
val HeritageRed = Color(0xFFE03C31)
val YRed = Color(0xFFE63C2F)
val light_AcidYellow = Color(0xFF616200)
val light_onAcidYellow = Color(0xFFFFFFFF)
val light_AcidYellowContainer = Color(0xFFE8EA30)
val light_onAcidYellowContainer = Color(0xFF1C1D00)
val dark_AcidYellow = Color(0xFFCCCD00)
val dark_onAcidYellow = Color(0xFF323200)
val dark_AcidYellowContainer = Color(0xFF494900)
val dark_onAcidYellowContainer = Color(0xFFE8EA30)
val light_HeritageRed = Color(0xFFB91E19)
val light_onHeritageRed = Color(0xFFFFFFFF)
val light_HeritageRedContainer = Color(0xFFFFDAD5)
val light_onHeritageRedContainer = Color(0xFF410001)
val dark_HeritageRed = Color(0xFFFFB4AA)
val dark_onHeritageRed = Color(0xFF690003)
val dark_HeritageRedContainer = Color(0xFF930006)
val dark_onHeritageRedContainer = Color(0xFFFFDAD5)
val light_YRed = Color(0xFFBA1A14)
val light_onYRed = Color(0xFFFFFFFF)
val light_YRedContainer = Color(0xFFFFDAD5)
val light_onYRedContainer = Color(0xFF410001)
val dark_YRed = Color(0xFFFFB4A9)
val dark_onYRed = Color(0xFF690002)
val dark_YRedContainer = Color(0xFF930004)
val dark_onYRedContainer = Color(0xFFFFDAD5)

 */