M48
; DRILL file KiCad 10.0.6 date 2026-09-13T12:04:02
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-13T12:04:02-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X38.344Y40.979
X38.344Y19.179
X98.044Y40.979
X98.044Y19.179
T2
X29.044Y12.459
M30
